#!/bin/bash
echo "==================================="
echo "🚀 AIzle Website is Ready!"
echo "==================================="
echo ""
echo "📁 File location: /workspace/aizle-landing.html"
echo "�� Local server: http://localhost:8080/aizle-landing.html"
echo ""
echo "📋 To view the website:"
echo "1. Copy the HTML content below"
echo "2. Save it as 'aizle.html' on your laptop"
echo "3. Double-click the file to open in browser"
echo ""
echo "==================================="
